#!/usr/bin/env python

import sys, os, re
from subprocess import check_output, CalledProcessError

# Collect the parameters
commit_msg_filepath = sys.argv[1]

# Figure out which branch we're on
try:
    branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip()
except CalledProcessError:
    # when rebasing
    branch = check_output(['cat', '.git/rebase-merge/head-name']).strip().split('/')[-1]

print "prepare-commit-msg: On branch '%s'" % branch

# Populate the commit message with the issue #, if there is one
if branch.startswith('BTY-'):
    print "prepare-commit-msg: Oh hey, it's an issue branch."
    result = re.match('([A-Z]{3}-[0-9]+)', branch)
    issue_number = "[%s]" % result.group(1)

    print issue_number

    with open(commit_msg_filepath, 'r+') as f:
        content = f.read()
        f.seek(0, 0)

        if not content.startswith(issue_number):
            f.write("%s %s" % (issue_number, content))
